server:
  port: 8081
  servlet:
    context-path: /yaml

book:
  id: 1
  name: 三国演义
  author: 罗贯中
  editors:
    - 张三
    - 李四
  chapters:
    - id: 1
      name: 第一章 桃园结义
    - id: 2
      name: 第二章 除董卓